# Generated by Django 5.0.7 on 2024-07-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
    ]
